{% set name = "xbatcher" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70b3da6e6277b57ef5ccfa56fa7e5e81c04d7f7e2bda671629653a7534a81970

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - xarray
    - dask
    - numpy

test:
  imports:
    - xbatcher
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/xbatcher
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Batch Generation from Xarray Datasets
  description: |
    Xbatcher is a small library for iterating xarray DataArrays in batches.
    The goal is to make it easy to feed xarray datasets to machine learning
    libraries such as PyTorch or TensorFlow.
  doc_url: https://xbatcher.readthedocs.io/en/latest
  dev_url: https://github.com/xarray-contrib/xbatcher

extra:
  recipe-maintainers:
    - maxrjones
    - jhamman
    - rabernat
