{% set python_min = '3.10' %}
{% set name = "xbatcher" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6744005c76699659586a92d35a497e327749b37aa441e941c07a696ec99b6a8f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - xarray
    - dask
    - numpy

test:
  imports:
    - xbatcher
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/xbatcher
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Batch Generation from Xarray Datasets
  description: |
    Xbatcher is a small library for iterating xarray DataArrays in batches.
    The goal is to make it easy to feed xarray datasets to machine learning
    libraries such as PyTorch or TensorFlow.
  doc_url: https://xbatcher.readthedocs.io/en/latest
  dev_url: https://github.com/xarray-contrib/xbatcher

extra:
  recipe-maintainers:
    - andersy005
    - maxrjones
    - jhamman
    - rabernat
